name: aula_inteligente
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animate_do: ^3.0.2
  flutter_animate: ^4.2.0
  flutter_svg: ^2.0.7
  glassmorphism_ui: ^0.3.0
  animated_text_kit: ^4.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
